[package]
name = "lru"
version = "0.1.0"
authors = ["Jack Drogon <jack.xsuperman@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.6.3"

[[bin]]
name = "lru"
path = "src/lru.rs"

[[bin]]
name = "iter"
path = "src/iter.rs"
